// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/user/pb/user.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e79bea15e155d9ac, []int{0}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	UserID               int64    `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	Err                  string   `protobuf:"bytes,3,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e79bea15e155d9ac, []int{1}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *UserResponse) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *UserResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

// 通过UserID获取用户
type UserGetRequest struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserGetRequest) Reset()         { *m = UserGetRequest{} }
func (m *UserGetRequest) String() string { return proto.CompactTextString(m) }
func (*UserGetRequest) ProtoMessage()    {}
func (*UserGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e79bea15e155d9ac, []int{2}
}

func (m *UserGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGetRequest.Unmarshal(m, b)
}
func (m *UserGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGetRequest.Marshal(b, m, deterministic)
}
func (m *UserGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGetRequest.Merge(m, src)
}
func (m *UserGetRequest) XXX_Size() int {
	return xxx_messageInfo_UserGetRequest.Size(m)
}
func (m *UserGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserGetRequest proto.InternalMessageInfo

func (m *UserGetRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

// 返回用户信息
type UserGetResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Err                  string   `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	UserID               int64    `protobuf:"varint,3,opt,name=userID,proto3" json:"userID,omitempty"`
	UserName             string   `protobuf:"bytes,4,opt,name=userName,proto3" json:"userName,omitempty"`
	Birthday             string   `protobuf:"bytes,5,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Sex                  int32    `protobuf:"varint,6,opt,name=sex,proto3" json:"sex,omitempty"`
	Avatar               string   `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	City                 string   `protobuf:"bytes,8,opt,name=city,proto3" json:"city,omitempty"`
	District             string   `protobuf:"bytes,9,opt,name=district,proto3" json:"district,omitempty"`
	Introduction         string   `protobuf:"bytes,10,opt,name=introduction,proto3" json:"introduction,omitempty"`
	RoleID               int32    `protobuf:"varint,11,opt,name=roleID,proto3" json:"roleID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserGetResponse) Reset()         { *m = UserGetResponse{} }
func (m *UserGetResponse) String() string { return proto.CompactTextString(m) }
func (*UserGetResponse) ProtoMessage()    {}
func (*UserGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e79bea15e155d9ac, []int{3}
}

func (m *UserGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserGetResponse.Unmarshal(m, b)
}
func (m *UserGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserGetResponse.Marshal(b, m, deterministic)
}
func (m *UserGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserGetResponse.Merge(m, src)
}
func (m *UserGetResponse) XXX_Size() int {
	return xxx_messageInfo_UserGetResponse.Size(m)
}
func (m *UserGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserGetResponse proto.InternalMessageInfo

func (m *UserGetResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *UserGetResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *UserGetResponse) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *UserGetResponse) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserGetResponse) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *UserGetResponse) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *UserGetResponse) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserGetResponse) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *UserGetResponse) GetDistrict() string {
	if m != nil {
		return m.District
	}
	return ""
}

func (m *UserGetResponse) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

func (m *UserGetResponse) GetRoleID() int32 {
	if m != nil {
		return m.RoleID
	}
	return 0
}

func init() {
	proto.RegisterType((*UserRequest)(nil), "pb.UserRequest")
	proto.RegisterType((*UserResponse)(nil), "pb.UserResponse")
	proto.RegisterType((*UserGetRequest)(nil), "pb.UserGetRequest")
	proto.RegisterType((*UserGetResponse)(nil), "pb.UserGetResponse")
}

func init() { proto.RegisterFile("api/user/pb/user.proto", fileDescriptor_e79bea15e155d9ac) }

var fileDescriptor_e79bea15e155d9ac = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4d, 0x6f, 0xe2, 0x30,
	0x10, 0xdd, 0x24, 0xc0, 0xc2, 0x80, 0x00, 0x79, 0x25, 0x64, 0x71, 0x42, 0x39, 0x71, 0x58, 0xc1,
	0x6a, 0xfb, 0x0f, 0x5a, 0x2a, 0xc4, 0x05, 0x55, 0xa9, 0x7a, 0xe9, 0xcd, 0x49, 0x46, 0xc2, 0x2a,
	0xc4, 0xae, 0xed, 0xd0, 0xf2, 0x73, 0xfa, 0x4f, 0x2b, 0x3b, 0x0e, 0x09, 0xa7, 0x9e, 0x32, 0x6f,
	0x3e, 0xde, 0x9b, 0x3c, 0x0f, 0xcc, 0x98, 0xe4, 0xeb, 0x52, 0xa3, 0x5a, 0xcb, 0xd4, 0x7d, 0x57,
	0x52, 0x09, 0x23, 0x48, 0x28, 0xd3, 0xf8, 0x11, 0x86, 0x2f, 0x1a, 0x55, 0x82, 0xef, 0x25, 0x6a,
	0x43, 0xe6, 0xd0, 0xb7, 0x0d, 0x05, 0x3b, 0x21, 0x0d, 0x16, 0xc1, 0x72, 0x90, 0x5c, 0xb1, 0xad,
	0x49, 0xa6, 0xf5, 0x87, 0x50, 0x39, 0x0d, 0xab, 0x5a, 0x8d, 0xe3, 0x27, 0x18, 0x55, 0x34, 0x5a,
	0x8a, 0x42, 0x23, 0x99, 0x41, 0x4f, 0xa1, 0x2e, 0x8f, 0xc6, 0xb1, 0xf4, 0x13, 0x8f, 0x6c, 0xde,
	0xf2, 0xed, 0x36, 0x8e, 0x21, 0x4a, 0x3c, 0x22, 0x53, 0x88, 0x50, 0x29, 0x1a, 0x39, 0x5a, 0x1b,
	0xc6, 0x4b, 0x18, 0x5b, 0xc6, 0x2d, 0x9a, 0x7a, 0xb7, 0x66, 0x36, 0x68, 0xcf, 0xc6, 0x5f, 0x21,
	0x4c, 0xae, 0xad, 0x3f, 0xe8, 0x7b, 0x9d, 0xf0, 0xaa, 0xd3, 0x62, 0x8d, 0x6e, 0x36, 0xf2, 0x4e,
	0xec, 0xad, 0x13, 0x9d, 0xc6, 0x89, 0xbd, 0x77, 0x22, 0xe5, 0xca, 0x1c, 0x72, 0x76, 0xa1, 0xdd,
	0xaa, 0x56, 0x63, 0xab, 0xa0, 0xf1, 0x93, 0xf6, 0x16, 0xc1, 0xb2, 0x9b, 0xd8, 0xd0, 0x2a, 0xb0,
	0x33, 0x33, 0x4c, 0xd1, 0xdf, 0xae, 0xd7, 0x23, 0x42, 0xa0, 0x93, 0x71, 0x73, 0xa1, 0x7d, 0x97,
	0x75, 0xb1, 0x65, 0xce, 0xb9, 0x36, 0x8a, 0x67, 0x86, 0x0e, 0x2a, 0xe6, 0x1a, 0x93, 0x18, 0x46,
	0xbc, 0x30, 0x4a, 0xe4, 0x65, 0x66, 0xb8, 0x28, 0x28, 0xb8, 0xfa, 0x4d, 0xce, 0xfd, 0xb7, 0x38,
	0xe2, 0x6e, 0x43, 0x87, 0x6e, 0x01, 0x8f, 0xfe, 0x9f, 0xaa, 0x67, 0x7e, 0x46, 0x75, 0xe6, 0x19,
	0x92, 0xbf, 0xd0, 0x7d, 0x38, 0x60, 0xf6, 0x46, 0x26, 0x2b, 0x99, 0xae, 0x5a, 0x07, 0x30, 0x9f,
	0x36, 0x89, 0xca, 0xca, 0xf8, 0x17, 0xf9, 0x07, 0xd1, 0x16, 0x0d, 0x21, 0x75, 0xa9, 0x79, 0x93,
	0xf9, 0x9f, 0x9b, 0x5c, 0x3d, 0x71, 0x3f, 0x7e, 0x1d, 0xad, 0x5b, 0x47, 0x97, 0xf6, 0xdc, 0xc1,
	0xdd, 0x7d, 0x07, 0x00, 0x00, 0xff, 0xff, 0xe7, 0x60, 0x02, 0x74, 0x8a, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	Check(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	Get(ctx context.Context, in *UserGetRequest, opts ...grpc.CallOption) (*UserGetResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Check(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/pb.UserService/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Get(ctx context.Context, in *UserGetRequest, opts ...grpc.CallOption) (*UserGetResponse, error) {
	out := new(UserGetResponse)
	err := c.cc.Invoke(ctx, "/pb.UserService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	Check(context.Context, *UserRequest) (*UserResponse, error)
	Get(context.Context, *UserGetRequest) (*UserGetResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) Check(ctx context.Context, req *UserRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (*UnimplementedUserServiceServer) Get(ctx context.Context, req *UserGetRequest) (*UserGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserService/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Check(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Get(ctx, req.(*UserGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _UserService_Check_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _UserService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/user/pb/user.proto",
}
