// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/oauth.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CheckTokenRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckTokenRequest) Reset()         { *m = CheckTokenRequest{} }
func (m *CheckTokenRequest) String() string { return proto.CompactTextString(m) }
func (*CheckTokenRequest) ProtoMessage()    {}
func (*CheckTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a064a29c17b5838, []int{0}
}

func (m *CheckTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckTokenRequest.Unmarshal(m, b)
}
func (m *CheckTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckTokenRequest.Marshal(b, m, deterministic)
}
func (m *CheckTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckTokenRequest.Merge(m, src)
}
func (m *CheckTokenRequest) XXX_Size() int {
	return xxx_messageInfo_CheckTokenRequest.Size(m)
}
func (m *CheckTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckTokenRequest proto.InternalMessageInfo

func (m *CheckTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ClientDetails struct {
	ClientId                    string   `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	AccessTokenValiditySeconds  int32    `protobuf:"varint,2,opt,name=accessTokenValiditySeconds,proto3" json:"accessTokenValiditySeconds,omitempty"`
	RefreshTokenValiditySeconds int32    `protobuf:"varint,3,opt,name=refreshTokenValiditySeconds,proto3" json:"refreshTokenValiditySeconds,omitempty"`
	AuthorizedGrantTypes        []string `protobuf:"bytes,4,rep,name=authorizedGrantTypes,proto3" json:"authorizedGrantTypes,omitempty"`
	XXX_NoUnkeyedLiteral        struct{} `json:"-"`
	XXX_unrecognized            []byte   `json:"-"`
	XXX_sizecache               int32    `json:"-"`
}

func (m *ClientDetails) Reset()         { *m = ClientDetails{} }
func (m *ClientDetails) String() string { return proto.CompactTextString(m) }
func (*ClientDetails) ProtoMessage()    {}
func (*ClientDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a064a29c17b5838, []int{1}
}

func (m *ClientDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientDetails.Unmarshal(m, b)
}
func (m *ClientDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientDetails.Marshal(b, m, deterministic)
}
func (m *ClientDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientDetails.Merge(m, src)
}
func (m *ClientDetails) XXX_Size() int {
	return xxx_messageInfo_ClientDetails.Size(m)
}
func (m *ClientDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientDetails.DiscardUnknown(m)
}

var xxx_messageInfo_ClientDetails proto.InternalMessageInfo

func (m *ClientDetails) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *ClientDetails) GetAccessTokenValiditySeconds() int32 {
	if m != nil {
		return m.AccessTokenValiditySeconds
	}
	return 0
}

func (m *ClientDetails) GetRefreshTokenValiditySeconds() int32 {
	if m != nil {
		return m.RefreshTokenValiditySeconds
	}
	return 0
}

func (m *ClientDetails) GetAuthorizedGrantTypes() []string {
	if m != nil {
		return m.AuthorizedGrantTypes
	}
	return nil
}

type UserDetails struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Authorities          []string `protobuf:"bytes,3,rep,name=authorities,proto3" json:"authorities,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserDetails) Reset()         { *m = UserDetails{} }
func (m *UserDetails) String() string { return proto.CompactTextString(m) }
func (*UserDetails) ProtoMessage()    {}
func (*UserDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a064a29c17b5838, []int{2}
}

func (m *UserDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDetails.Unmarshal(m, b)
}
func (m *UserDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDetails.Marshal(b, m, deterministic)
}
func (m *UserDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDetails.Merge(m, src)
}
func (m *UserDetails) XXX_Size() int {
	return xxx_messageInfo_UserDetails.Size(m)
}
func (m *UserDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDetails.DiscardUnknown(m)
}

var xxx_messageInfo_UserDetails proto.InternalMessageInfo

func (m *UserDetails) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserDetails) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserDetails) GetAuthorities() []string {
	if m != nil {
		return m.Authorities
	}
	return nil
}

type CheckTokenResponse struct {
	UserDetails          *UserDetails   `protobuf:"bytes,1,opt,name=userDetails,proto3" json:"userDetails,omitempty"`
	ClientDetails        *ClientDetails `protobuf:"bytes,2,opt,name=clientDetails,proto3" json:"clientDetails,omitempty"`
	IsValidToken         bool           `protobuf:"varint,3,opt,name=isValidToken,proto3" json:"isValidToken,omitempty"`
	Err                  string         `protobuf:"bytes,4,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CheckTokenResponse) Reset()         { *m = CheckTokenResponse{} }
func (m *CheckTokenResponse) String() string { return proto.CompactTextString(m) }
func (*CheckTokenResponse) ProtoMessage()    {}
func (*CheckTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a064a29c17b5838, []int{3}
}

func (m *CheckTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckTokenResponse.Unmarshal(m, b)
}
func (m *CheckTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckTokenResponse.Marshal(b, m, deterministic)
}
func (m *CheckTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckTokenResponse.Merge(m, src)
}
func (m *CheckTokenResponse) XXX_Size() int {
	return xxx_messageInfo_CheckTokenResponse.Size(m)
}
func (m *CheckTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckTokenResponse proto.InternalMessageInfo

func (m *CheckTokenResponse) GetUserDetails() *UserDetails {
	if m != nil {
		return m.UserDetails
	}
	return nil
}

func (m *CheckTokenResponse) GetClientDetails() *ClientDetails {
	if m != nil {
		return m.ClientDetails
	}
	return nil
}

func (m *CheckTokenResponse) GetIsValidToken() bool {
	if m != nil {
		return m.IsValidToken
	}
	return false
}

func (m *CheckTokenResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*CheckTokenRequest)(nil), "pb.CheckTokenRequest")
	proto.RegisterType((*ClientDetails)(nil), "pb.ClientDetails")
	proto.RegisterType((*UserDetails)(nil), "pb.UserDetails")
	proto.RegisterType((*CheckTokenResponse)(nil), "pb.CheckTokenResponse")
}

func init() { proto.RegisterFile("pb/oauth.proto", fileDescriptor_8a064a29c17b5838) }

var fileDescriptor_8a064a29c17b5838 = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xc1, 0x4e, 0xea, 0x40,
	0x14, 0x86, 0x53, 0x0a, 0x04, 0x4e, 0xe1, 0xde, 0xcb, 0x84, 0x4b, 0x1a, 0xee, 0xa6, 0xe9, 0x8a,
	0xbb, 0x81, 0x58, 0x17, 0x2e, 0x4c, 0x8c, 0x8a, 0x89, 0x31, 0x2e, 0x4c, 0x06, 0x74, 0xe1, 0xae,
	0x9d, 0x1e, 0xd3, 0x09, 0xd8, 0xd6, 0x99, 0xa9, 0x09, 0x3e, 0x98, 0xef, 0xe3, 0x9b, 0x98, 0x19,
	0x2a, 0x14, 0x42, 0xd8, 0xcd, 0x7f, 0xfa, 0xf7, 0x9c, 0xff, 0x3b, 0x33, 0xf0, 0x2b, 0x8f, 0x26,
	0x59, 0x58, 0xa8, 0x64, 0x9c, 0x8b, 0x4c, 0x65, 0xa4, 0x96, 0x47, 0xfe, 0x7f, 0xe8, 0x4d, 0x13,
	0x64, 0x8b, 0x79, 0xb6, 0xc0, 0x94, 0xe2, 0x5b, 0x81, 0x52, 0x91, 0x3e, 0x34, 0x94, 0xd6, 0xae,
	0xe5, 0x59, 0xa3, 0x36, 0x5d, 0x0b, 0xff, 0xcb, 0x82, 0xee, 0x74, 0xc9, 0x31, 0x55, 0x37, 0xa8,
	0x42, 0xbe, 0x94, 0x64, 0x08, 0x2d, 0x66, 0x0a, 0x77, 0x71, 0x69, 0xdd, 0x68, 0x72, 0x01, 0xc3,
	0x90, 0x31, 0x94, 0xd2, 0x74, 0x7e, 0x0a, 0x97, 0x3c, 0xe6, 0x6a, 0x35, 0x43, 0x96, 0xa5, 0xb1,
	0x74, 0x6b, 0x9e, 0x35, 0x6a, 0xd0, 0x23, 0x0e, 0x72, 0x09, 0xff, 0x04, 0xbe, 0x08, 0x94, 0xc9,
	0xc1, 0x06, 0xb6, 0x69, 0x70, 0xcc, 0x42, 0x02, 0xe8, 0x6b, 0xd8, 0x4c, 0xf0, 0x0f, 0x8c, 0x6f,
	0x45, 0x98, 0xaa, 0xf9, 0x2a, 0x47, 0xe9, 0xd6, 0x3d, 0x7b, 0xd4, 0xa6, 0x07, 0xbf, 0xf9, 0x0c,
	0x9c, 0x47, 0x89, 0xe2, 0x07, 0x70, 0x00, 0xcd, 0x42, 0xa2, 0x28, 0xf1, 0x6c, 0x5a, 0x2a, 0x0d,
	0xae, 0x4f, 0x69, 0xf8, 0x8a, 0x06, 0xa5, 0x4d, 0x37, 0x9a, 0x78, 0xe0, 0x94, 0xad, 0x15, 0x47,
	0x1d, 0x54, 0x4f, 0xab, 0x96, 0xfc, 0x4f, 0x0b, 0x48, 0x75, 0xe9, 0x32, 0xcf, 0x52, 0x89, 0xe4,
	0x04, 0x9c, 0x62, 0x3b, 0xdb, 0x4c, 0x74, 0x82, 0xdf, 0xe3, 0x3c, 0x1a, 0x57, 0x22, 0xd1, 0xaa,
	0x87, 0x9c, 0x41, 0x97, 0x55, 0x6f, 0xc4, 0x84, 0x71, 0x82, 0x9e, 0xfe, 0x69, 0xe7, 0xaa, 0xe8,
	0xae, 0x8f, 0xf8, 0xd0, 0xe1, 0xd2, 0x2c, 0xcc, 0x64, 0x30, 0xeb, 0x6c, 0xd1, 0x9d, 0x1a, 0xf9,
	0x03, 0x36, 0x0a, 0xe1, 0xd6, 0x0d, 0x9f, 0x3e, 0x06, 0xf7, 0xd0, 0x79, 0xb8, 0x2a, 0x54, 0x32,
	0x43, 0xf1, 0xce, 0x19, 0x92, 0x73, 0x80, 0x2d, 0x07, 0xf9, 0x6b, 0xa6, 0xee, 0x3f, 0xa6, 0xe1,
	0x60, 0xbf, 0xbc, 0xc6, 0xbd, 0x6e, 0x3c, 0xdb, 0x93, 0x3c, 0x8a, 0x9a, 0xe6, 0x2d, 0x9e, 0x7e,
	0x07, 0x00, 0x00, 0xff, 0xff, 0x60, 0x5b, 0x5b, 0xf9, 0x9d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OAuthServiceClient is the client API for OAuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OAuthServiceClient interface {
	// token 校验
	CheckToken(ctx context.Context, in *CheckTokenRequest, opts ...grpc.CallOption) (*CheckTokenResponse, error)
}

type oAuthServiceClient struct {
	cc *grpc.ClientConn
}

func NewOAuthServiceClient(cc *grpc.ClientConn) OAuthServiceClient {
	return &oAuthServiceClient{cc}
}

func (c *oAuthServiceClient) CheckToken(ctx context.Context, in *CheckTokenRequest, opts ...grpc.CallOption) (*CheckTokenResponse, error) {
	out := new(CheckTokenResponse)
	err := c.cc.Invoke(ctx, "/pb.OAuthService/CheckToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OAuthServiceServer is the server API for OAuthService service.
type OAuthServiceServer interface {
	// token 校验
	CheckToken(context.Context, *CheckTokenRequest) (*CheckTokenResponse, error)
}

// UnimplementedOAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOAuthServiceServer struct {
}

func (*UnimplementedOAuthServiceServer) CheckToken(ctx context.Context, req *CheckTokenRequest) (*CheckTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckToken not implemented")
}

func RegisterOAuthServiceServer(s *grpc.Server, srv OAuthServiceServer) {
	s.RegisterService(&_OAuthService_serviceDesc, srv)
}

func _OAuthService_CheckToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthServiceServer).CheckToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OAuthService/CheckToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthServiceServer).CheckToken(ctx, req.(*CheckTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OAuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.OAuthService",
	HandlerType: (*OAuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckToken",
			Handler:    _OAuthService_CheckToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/oauth.proto",
}
